name: Crawl bugbounty platforms

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite ejecución manual si es necesario

jobs:
  run_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore progress
        uses: actions/download-artifact@v4
        with:
          name: progreso
          path: programs/  # Restaurar archivos en la carpeta correcta
        continue-on-error: true  # Evita fallos si no hay progreso guardado

      - name: Debug - List restored files
        run: ls -la programs/

      - name: Run crawler
        env:
          HACKERONE_USERNAME: ${{ secrets.HACKERONE_USERNAME }}
          HACKERONE_TOKEN: ${{ secrets.HACKERONE_TOKEN }}
        run: |
          python main.py # Asume que tu script soporta reanudar

      - name: Debug - List files
        run: ls -la programs/

      - name: Save progress
        uses: actions/upload-artifact@v4
        with:
          name: progreso
          path: programs/ # Guarda todos los archivos JSON de progreso
        if: always()

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update programs to the latest version" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
