name: Crawl bugbounty platforms

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite ejecución manual si es necesario

jobs:
  run_and_push:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours to allow for cleanup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create progress directory
        run: |
          mkdir -p progress
          touch progress/.gitkeep

      - name: Restore progress from repository
        run: |
          if [ -f "progress/hackerone_progress.json" ]; then
            echo "Found existing progress file"
          else
            echo "No existing progress file found"
          fi

      - name: Run crawler
        env:
          HACKERONE_USERNAME: ${{ secrets.HACKERONE_USERNAME }}
          HACKERONE_TOKEN: ${{ secrets.HACKERONE_TOKEN }}
        run: |
          python main.py

      - name: Debug - List files
        run: |
          echo "Contents of progress directory:"
          ls -la progress/
          echo "Contents of programs directory:"
          ls -la programs/

      - name: Commit and push progress
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add progress/
          git commit -m "Update progress files" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

      - name: Commit and push programs
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add programs/
          git commit -m "Update programs to the latest version" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
